---
title: "git_00"
author: "Cyann Arevalo"
date: "September 1, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
  
   Just the place for a Snark!" the Bellman cried,  
  As he landed his crew with care;  
  Supporting each man on the top of the tide  
  By a finger entwined in his hair.  

  Just the place for a Snark! I have said it twice:    

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
  
  A lantern light from deeper in the barn  
  Shone on a man and woman in the door  
  And threw their lurching shadows on a house  
  Near by, all dark in every glossy window.  
  A horse's hoof pawed once the hollow floor,  
   
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
  
  The sun was shining on the sea,  
  Shining with all his might:  
  He did his very best to make  
  The billows smooth and bright--  
  And this was odd, because it was  
  The middle of the night.  
    
  The moon was shining sulkily,  
  Because she thought the sun  
  Had got no business to be there  
  After the day was done--  
  "It's very rude of him," she said,  
  "To come and spoil the fun!"  
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

  But evil things, in robes of sorrow,  
  Assailed the monarch’s high estate;   
  (Ah, let us mourn!—for never morrow  
  Shall dawn upon him, desolate!)  
  And round about his home the glory  
  That blushed and bloomed  
  Is but a dim-remembered story  
  Of the old time entombed.  